// <auto-generated />
using System;
using Loto.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Loto.Infrastructure.Migrations
{
    [DbContext(typeof(LotoDbContext))]
    [Migration("20251202123526_AddOfficialDrawFields")]
    partial class AddOfficialDrawFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Loto.Domain.Draw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LuckyNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Number1")
                        .HasColumnType("integer");

                    b.Property<int>("Number2")
                        .HasColumnType("integer");

                    b.Property<int>("Number3")
                        .HasColumnType("integer");

                    b.Property<int>("Number4")
                        .HasColumnType("integer");

                    b.Property<int>("Number5")
                        .HasColumnType("integer");

                    b.Property<string>("OfficialDrawId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OfficialDrawId")
                        .IsUnique();

                    b.HasIndex("DrawDate", "Number1", "Number2", "Number3", "Number4", "Number5", "LuckyNumber")
                        .IsUnique();

                    b.ToTable("Draws", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
